---
primary_user: jsantos
users:
  - name: "{{primary_user}}"
    groups:
      - docker
    authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDHAB3+8HZ+7tDYrU59Yx8bFQZurNKR3qiqzaHuXZLzulnd4dVt5Eei91vESnNiMD4KEuvKFiGyqknMJHuEUFoESVj3Q9iogXt8lNwTSZ2TahX5zcVE9Nxh8rwTgP5MpuFipj/NYEc2+CNjipcnmAk7YdhczuVkf+gatUbfi8aTDq8hDLuDO5GxE1He9/TzGPAPBnzIE2hJCOpV5yIXH9okcAA1jbZnpjBqLLyxCVTi0tYxuoi2eNk2PbeborltKeuQi8cJj1vFU4O8Mh+3PqFCv3buWwB6sW73gqdx8ybEvCdbwaqnIRBM2oSqxO0deEU2lcSrp1DRAo5OJ4Gfk2pTCZFHcIv9QNoo1hKiv2OwYfesd7wMUbqpuec1cpZpYWFX14bhj0WWw2L8awdyTtCx6S1L1mdOfQK3IRmXd6F8duePN/OCAmHlHArzWS7QpuPsVxL4/bR84vobsuGaj+jCxi1z58Ml9gJT2rb7790g6lzmem37/ghccEnIs5yth8c= josh@omnidapps.com
    pubkeys: {} # { name: key_name, content: "ssh-rsa..." }
    home: "/home/{{primary_user}}"
